# Use the latest 2.1 version of CircleCI pipeline processing engine, see https://circleci.com/docs/2.0/configuration-reference/
version: 2.1

defaults: &defaults
  docker:
    - image: cimg/node:18.18
      environment:
        TERM: xterm # Enable colors in term
        QUICK_BUILD: true
  working_directory: ~/repo

jobs:
  CHECKOUT:
    <<: *defaults
    steps:
      - checkout
      - run: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
      - restore_cache:
          name: Restore Package Cache
          keys:
            - packages-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - packages-v1-{{ .Branch }}-
            - packages-v1-
      - run: yarn install --frozen-lockfile
      - save_cache:
          name: Save Package Cache
          paths:
            - ~/.cache/yarn
          key: packages-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - persist_to_workspace:
          root: ~/repo
          paths: .

  BUILD:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: 'Perform the versioning before build'
          command: node ./version.mjs
      - run: yarn run build
      - persist_to_workspace:
          root: ~/repo
          paths:
            - packages/core/dist
            - packages/tools/dist
            - packages/streaming-image-volume-loader/dist
            - packages/adapters/dist

  NPM_PUBLISH:
    <<: *defaults
    steps:
      - run: yarn -v
      # Checkout code and ALL Git Tags
      - checkout
      - attach_workspace:
          at: ~/repo
      # Use increasingly general patterns to restore cache
      - restore_cache:
          name: Restore Yarn and Cypress Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
            - yarn-packages-
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          name: Save Yarn Package Cache
          paths:
            - ~/.cache/yarn
          key: yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Avoid hosts unknown for github
          command: |
            rm -rf ~/.ssh
            mkdir ~/.ssh/
            echo -e "Host github.com\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
            git config --global user.email "danny.ri.brown+ohif-bot@gmail.com"
            git config --global user.name "ohif-bot"
      - run:
          name: Authenticate with NPM registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/repo/.npmrc
      - run:
          name: build half of the packages (to avoid out of memory in circleci)
          command: |
            yarn run build
      - run:
          name: publish package versions
          command: |
            node ./publish-version.mjs
      - run:
          name: Again set the NPM registry (was deleted in the version script)
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/repo/.npmrc
      - run:
          name: publish package dist
          command: |
            node ./publish-package.mjs
      - persist_to_workspace:
          root: ~/repo
          paths:
            - .
workflows:
  version: 2

  # PULL REQUEST
  PULL_REQUEST:
    jobs:
      - CHECKOUT:
          filters:
            branches:
              ignore:
                - main
                - feature/*
                - hotfix/*
      - BUILD:
          requires:
            - CHECKOUT

  # MERGE TO MAIN
  TEST_AND_PUBLISH_MASTER:
    jobs:
      - CHECKOUT:
          filters:
            branches:
              only: main
      - BUILD:
          requires:
            - CHECKOUT
      - NPM_PUBLISH:
          requires:
            - BUILD

  # MERGE TO RELEASE
  TEST_AND_PUBLISH_RELEASE:
    jobs:
      - CHECKOUT:
          filters:
            branches:
              only: release
      - BUILD:
          requires:
            - CHECKOUT
      - NPM_PUBLISH:
          requires:
            - BUILD

# VS Code Extension Version: 1.5.1
